development:
  db:
    host:
    port:
    username:
    password:
    db_name:
  redis:
    host:
    port:
    ttl_model: # Minutes
  api:
    url:
    key:
    secret:
  secret_key: # JSON file
  bucket_name:
